#!/usr/bin/env ruby

dst = ARGV[0]
src = ARGV[1]

`ghc --make -dynamic -shared -fPIC -o #{dst} include/value.hs include/ffi.hs #{src}`

dir = src.slice(/.*\//).chop
`rm #{dir}/*.o`
`rm include/*.o include/*.hi`
